### ISSUE TITLE
Popularity jumps to 75

### ISSUE THREAD

**Issue by TheAceOfInsanity** [UnofficialCrusaderPatch/UnofficialCrusaderPatch2#1044]
I encountered a popularity bug awhile back where I would have a popularity in the red and somehow I did something or I placed something that shot the popularity artificially to 75. To enphasize, I don't mean that the popularity gradually went to 75, it went there immediately. I tried to replicate it but I don't know how to; it seems to be working just fine now but I thought I'd make this report anyway. I'm pretty sure I saw it happen in one of Jefflenious' Crusader challenges but I could be wrong.

**Comment by GRhin** [comment]
This happens when you have less than 4 workers. It is not a bug, but a
feature. If you have that few workers and 0 popularity your probably dead,
resetting to 75 gives you half a chance to recover.

**Comment by TheAceOfInsanity** [comment]
Ahh. I understand. Thank you sir
